### ISSUE TITLE
parent_exec -> Invalid read of size

### ISSUE THREAD

**Issue by bfiguet** [3lsy/minishell#18]
ex ls | ls
Invalid read of size 4
==27074==    at 0x10A91A: parent_exec
==27074==    by 0x10AB0C: ft_evaluator
==27074==    by 0x1093FD: main 
==27074==  Address 0x10c1d088 is 0 bytes after a block of size 8 alloc'd
==27074==    at 0x895F899: malloc 
==27074==    by 0x10E45C: ft_calloc 
==27074==    by 0x10AABA: ft_evaluator

**Comment by bfiguet** [comment]
no problm for ls|ls

**Comment by 3lsy** [comment]
Done
